const viewerRoutes = require("./viewerRoutes");
const userRoutes = require("./userRoutes");
const projectRoutes = require("./projectRoutes");
const pageRoutes = require("./pageRoutes");
const designRoutes = require("./designRoutes");
const taskRoutes = require("./taskRoutes");
const commentRoutes = require("./commentRoutes");
const trashRoutes = require("./trashRoutes");
const generalRoutes = require("./generalRoutes");
const proxyRoutes = require("./proxyRoutes");
module.exports = function(app) {
  generalRoutes(app);
  viewerRoutes(app);
  userRoutes(app);
  projectRoutes(app);
  pageRoutes(app);
  designRoutes(app);
  taskRoutes(app);
  commentRoutes(app);
  trashRoutes(app);
  proxyRoutes(app);
};
