---
- hosts: local
  vars:
    server_url: perfect-pixel.local
    document_root: /perfect-pixel-app
    current_user: root

    nodejs_version: "12.x"

  vars_files:
    - vars/mysql-vars.yml

  become: true
  remote_user: "{{current_user}}"

  roles:
    - python
    - role: geerlingguy.mysql
    - role: geerlingguy.nodejs
    - role: ocha.yarn
    - environment
    - yarn
    - server

- hosts: vagrant
  vars:
    server_url: perfect-pixel.local
    document_root: /perfect-pixel-app
    current_user: vagrant

    nodejs_version: "12.x"

  vars_files:
    - vars/mysql-vars.yml

  become: true
  remote_user: "{{current_user}}"

  roles:
    - python
    - role: geerlingguy.mysql
    - role: geerlingguy.nodejs
    - role: ocha.yarn
    - environment
    - yarn
    - server

- hosts: stage
  vars:
    server_url: perfectpixel.io
    document_root: /perfect-pixel-app
    current_user: root

    nodejs_version: "12.x"

  vars_files:
    - vars/mysql-vars.yml

  become: true
  remote_user: "{{current_user}}"

  roles:
    - git
    - python
    - role: geerlingguy.mysql
    - role: geerlingguy.nodejs
    - role: ocha.yarn
    - environment
    - yarn
    - server