export const EXTENSION_SET_PORT = "EXTENSION_SET_PORT";
export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_CHECK_AUTH = "AUTH_CHECK_AUTH";

export const USER_REQUEST = "USER_REQUEST";

export const INSPECTOR_SET_DESIGN = "INSPECTOR_SET_DESIGN";
export const INSPECTOR_SET_WEBSITE_URL = "INSPECTOR_SET_WEBSITE_URL";
export const INSPECTOR_SET_FRAME_PARAMS = "INSPECTOR_SET_FRAME_PARAMS";
export const INSPECTOR_SET_VIEW_PARAMS = "INSPECTOR_SET_VIEW_PARAMS";
export const INSPECTOR_SET_FOUND_NODES = "INSPECTOR_SET_FOUND_NODES";
export const INSPECTOR_SET_CURRENT_FRAME = "INSPECTOR_SET_CURRENT_FRAME";
export const INSPECTOR_RESET_DESIGN = "INSPECTOR_RESET_DESIGN";
export const INSPECTOR_SET_TARGET_ELEMENT = "INSPECTOR_SET_TARGET_ELEMENT";

export const PROJECT_SET_CURRENT_PROJECT = "PROJECT_SET_CURRENT_PROJECT";
export const PROJECT_CREATE_PROJECT = "PROJECT_CREATE_PROJECT";
export const PROJECT_EDIT_PROJECT = "PROJECT_EDIT_PROJECT";
export const PROJECT_GET_ALL_PROJECTS = "PROJECT_GET_ALL_PROJECTS";
export const PROJECT_MOVE_TO_TRASH = "PROJECT_MOVE_TO_TRASH";

export const PAGE_SET_CURRENT_PAGE = "PAGE_SET_CURRENT_PAGE";
export const PAGE_CREATE_PAGE = "PAGE_CREATE_PAGE";
export const PAGE_EDIT_PAGE = "PAGE_EDIT_PAGE";
export const PAGE_GET_PAGES = "PAGE_GET_PAGES";
export const PAGE_GET_PAGE = "PAGE_GET_PAGE";
export const PAGE_MOVE_TO_TRASH = "PAGE_MOVE_TO_TRASH";

export const TRASH_GET_PROJECTS_TRASH = "TRASH_GET_PROJECTS_TRASH";
export const TRASH_RESTORE_PROJECT = "TRASH_RESTORE_PROJECT";
export const TRASH_DELETE_PROJECT = "TRASH_DELETE_PROJECT";
export const TRASH_GET_PAGES_TRASH = "TRASH_GET_PAGES_TRASH";
export const TRASH_RESTORE_PAGE = "TRASH_RESTORE_PAGE";
export const TRASH_DELETE_PAGE = "TRASH_DELETE_PAGE";
