export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const USER_REQUEST = "USER_REQUEST";

export const INSPECTOR_SET_DESIGN = "INSPECTOR_SET_DESIGN";
export const INSPECTOR_SET_WEBSITE_URL = "INSPECTOR_SET_WEBSITE_URL";
export const INSPECTOR_SET_FRAME_PARAMS = "INSPECTOR_SET_FRAME_PARAMS";
export const INSPECTOR_SET_VIEW_PARAMS = "INSPECTOR_SET_VIEW_PARAMS";
export const INSPECTOR_SET_FOUND_NODES = "INSPECTOR_SET_FOUND_NODES";
export const INSPECTOR_SET_CURRENT_FRAME = "INSPECTOR_SET_CURRENT_FRAME";
export const INSPECTOR_RESET_DESIGN = "INSPECTOR_RESET_DESIGN";
export const INSPECTOR_SET_TARGET_ELEMENT = "INSPECTOR_SET_TARGET_ELEMENT";

export const PROJECT_SET_PROJECT_INFO = "PROJECT_SET_PROJECT_INFO";
export const PROJECT_SET_CURRENT_PROJECT = "PROJECT_SET_CURRENT_PROJECT";
