export const EXTENSION_SET_PORT = "EXTENSION_SET_PORT";
export const USER_LOGIN = "USER_LOGIN";
export const USER_REGISTER = "USER_REGISTER";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS";
export const USER_AUTH_ERROR = "USER_AUTH_ERROR";
export const USER_CHECK_AUTH = "USER_CHECK_AUTH";
export const USER_CHECK_USER_EXIST = "USER_CHECK_USER_EXIST";

export const INSPECTOR_SET_DESIGN = "INSPECTOR_SET_DESIGN";
export const INSPECTOR_SET_FOUND_NODES = "INSPECTOR_SET_FOUND_NODES";
export const INSPECTOR_SET_TARGET_ELEMENT = "INSPECTOR_SET_TARGET_ELEMENT";
export const INSPECTOR_SET_STATE = "INSPECTOR_SET_STATE";
export const INSPECTOR_SET_STATUS = "INSPECTOR_SET_STATUS";
export const INSPECTOR_SET_TOOL = "INSPECTOR_SET_TOOL";

export const PROJECT_SET_CURRENT_PROJECT = "PROJECT_SET_CURRENT_PROJECT";
export const PROJECT_CREATE_PROJECT = "PROJECT_CREATE_PROJECT";
export const PROJECT_EDIT_PROJECT = "PROJECT_EDIT_PROJECT";
export const PROJECT_SET_SCREENSHOT = "PROJECT_SET_SCREENSHOT";
export const PROJECT_GET_PROJECTS = "PROJECT_GET_PROJECTS";
export const PROJECT_MOVE_TO_TRASH = "PROJECT_MOVE_TO_TRASH";
export const PROJECT_CHECK_ACCESS = "PROJECT_CHECK_ACCESS";
export const PROJECT_INVITE_TO_PROJECT = "PROJECT_INVITE_TO_PROJECT";

export const PAGE_SET_CURRENT_PAGE = "PAGE_SET_CURRENT_PAGE";
export const PAGE_CREATE_PAGE = "PAGE_CREATE_PAGE";
export const PAGE_EDIT_PAGE = "PAGE_EDIT_PAGE";
export const PAGE_GET_PAGES = "PAGE_GET_PAGES";
export const PAGE_GET_PAGE = "PAGE_GET_PAGE";

export const TASK_CREATE_TASK = "TASK_CREATE_TASK";
export const TASK_EDIT_TASK = "TASK_EDIT_TASK";
export const TASK_GET_ALL_TASKS = "TASK_GET_ALL_TASKS";
export const TASK_MOVE_TO_TRASH = "TASK_MOVE_TO_TRASH";
export const TASK_SET_CURRENT_TASK = "TASK_SET_CURRENT_TASK";

export const TRASH_GET_PROJECTS_TRASH = "TRASH_GET_PROJECTS_TRASH";
export const TRASH_RESTORE_PROJECT = "TRASH_RESTORE_PROJECT";
export const TRASH_DELETE_PROJECT = "TRASH_DELETE_PROJECT";
export const TRASH_DELETE_PAGE = "TRASH_DELETE_PAGE";

export const TRASH_GET_TASKS_TRASH = "TRASH_GET_TASKS_TRASH";
export const TRASH_RESTORE_TASK = "TRASH_RESTORE_TASK";
export const TRASH_DELETE_TASK = "TRASH_DELETE_TASK";
